apiVersion: core.openmfp.io/v1alpha1
kind: Account
metadata:
  name: my-account
  namespace: default
spec:
  displayName: "My Account"
  type: "account"  # Must be either 'folder' or 'account' as per the enum
  creator: "user@example.com"  # The initial creator of this account
  description: "This is an example account"
  namespace: "my-account-namespace"  # Namespace the account should take ownership of
  data:
    additionalInfo1: "value1"
    additionalInfo2: "value2"
  extensions:
    - apiVersion: extension.example.com/v1
      kind: CustomExtension
      readyConditionType: "Ready"  # Condition type to check for readiness
      specGoTemplate:
        field1: "value1"
        field2: "value2"
