issue-845-fix: true
resolve-type-alias: false
with-expecter: true
packages:
  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      dir: gateway/resolver/mocks
      outpkg: mocks
    interfaces:
      WithWatch:
  net/http:
    config:
      dir: gateway/manager/mocks
      outpkg: mocks
    interfaces:
      RoundTripper:

