exclude:
  paths:
    - main.go
    - cmd
    - tests
    - common/config/config.go
    - deprecated/*
    - mocks
    # the following files should be excluded from coverage later
    - listener/apischema/*
    - listener/controller/*
