exclude:
  paths:
    - main.go
    - cmd
    - tests
    - common/config/config.go
    - mocks
    - common/apis/*
    # remove it later:
    - listener/reconciler/multicluster/subroutines.go
    - listener/reconciler/singlecluster
    - listener/reconciler/kcp
