exclude:
  paths:
    # no need to cover it with tests
    - main.go
    - cmd
    - deprecated
    - tests
    - gateway/config/config.go
    # To be covered later
    - listener/*
    - gateway/manager/roundtripper.go
