exclude:
  paths:
    - main.go
    - cmd
    - tests
    - common/config/config.go
    - mocks
    # the following files should be excluded from coverage later
    # - listener/apischema/*
    # - listener/controller/*
