package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ClusterAccessSpec defines the desired state of ClusterAccess
type ClusterAccessSpec struct {
	// Path is an optional field. If not set, the name of the resource is used
	// +optional
	Path string `json:"path,omitempty"`

	// Host is the URL for the cluster
	Host string `json:"host"`

	// CA configuration for the cluster
	// +optional
	CA *CAConfig `json:"ca,omitempty"`

	// Auth configuration for the cluster
	// +optional
	Auth *AuthConfig `json:"auth,omitempty"`
}

// CAConfig defines CA configuration options
type CAConfig struct {
	// SecretRef points to a secret containing CA data
	// +optional
	SecretRef *SecretRef `json:"secretRef,omitempty"`

	// ConfigMapRef points to a config map containing CA data
	// +optional
	ConfigMapRef *ConfigMapRef `json:"configMapRef,omitempty"`
}

// AuthConfig defines authentication configuration options
type AuthConfig struct {
	// SecretRef points to a secret containing auth token
	// +optional
	SecretRef *SecretRef `json:"secretRef,omitempty"`

	// KubeconfigSecretRef points to a secret containing kubeconfig
	// +optional
	KubeconfigSecretRef *KubeconfigSecretRef `json:"kubeconfigSecretRef,omitempty"`

	// ServiceAccount is the name of the service account to use
	// +optional
	ServiceAccount string `json:"serviceAccount,omitempty"`

	// ClientCertificateRef points to secrets containing client certificate and key for mTLS
	// +optional
	ClientCertificateRef *ClientCertificateRef `json:"clientCertificateRef,omitempty"`
}

// SecretRef defines a reference to a secret
type SecretRef struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
	Key       string `json:"key"`
}

// ConfigMapRef defines a reference to a config map
type ConfigMapRef struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
	Key       string `json:"key"`
}

// KubeconfigSecretRef defines a reference to a kubeconfig secret
type KubeconfigSecretRef struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
}

// ClientCertificateRef defines a reference to a client certificate secret
type ClientCertificateRef struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
}

// ClusterAccessStatus defines the observed state of ClusterAccess
type ClusterAccessStatus struct {
	// Conditions represent the latest available observations of the cluster access state
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:resource:scope=Cluster,shortName=ca

// ClusterAccess is the Schema for the clusteraccesses API
type ClusterAccess struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ClusterAccessSpec   `json:"spec,omitempty"`
	Status ClusterAccessStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// ClusterAccessList contains a list of ClusterAccess
type ClusterAccessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterAccess `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ClusterAccess{}, &ClusterAccessList{})
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAccess) DeepCopyInto(out *ClusterAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAccess.
func (in *ClusterAccess) DeepCopy() *ClusterAccess {
	if in == nil {
		return nil
	}
	out := new(ClusterAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAccessList) DeepCopyInto(out *ClusterAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAccessList.
func (in *ClusterAccessList) DeepCopy() *ClusterAccessList {
	if in == nil {
		return nil
	}
	out := new(ClusterAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterAccessSpec) DeepCopyInto(out *ClusterAccessSpec) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(CAConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthConfig)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ClusterAccessSpec) DeepCopy() *ClusterAccessSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAccessSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterAccessStatus) DeepCopyInto(out *ClusterAccessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterAccessStatus) DeepCopy() *ClusterAccessStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterAccessStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *CAConfig) DeepCopyInto(out *CAConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapRef)
		**out = **in
	}
}

func (in *CAConfig) DeepCopy() *CAConfig {
	if in == nil {
		return nil
	}
	out := new(CAConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.KubeconfigSecretRef != nil {
		in, out := &in.KubeconfigSecretRef, &out.KubeconfigSecretRef
		*out = new(KubeconfigSecretRef)
		**out = **in
	}
	if in.ClientCertificateRef != nil {
		in, out := &in.ClientCertificateRef, &out.ClientCertificateRef
		*out = new(ClientCertificateRef)
		**out = **in
	}
}

func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

func (in *KubeconfigSecretRef) DeepCopyInto(out *KubeconfigSecretRef) {
	*out = *in
}

func (in *KubeconfigSecretRef) DeepCopy() *KubeconfigSecretRef {
	if in == nil {
		return nil
	}
	out := new(KubeconfigSecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *ClientCertificateRef) DeepCopyInto(out *ClientCertificateRef) {
	*out = *in
}

func (in *ClientCertificateRef) DeepCopy() *ClientCertificateRef {
	if in == nil {
		return nil
	}
	out := new(ClientCertificateRef)
	in.DeepCopyInto(out)
	return out
}
