apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusteraccesses.gateway.openmfp.org
spec:
  group: gateway.openmfp.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - host
            properties:
              path:
                type: string
                description: "Optional path for the cluster access. If not set, the name of the resource is used"
              host:
                type: string
                description: "The host URL for the cluster"
              ca:
                type: object
                oneOf:
                - required: [secretRef]
                - required: [configMapRef]
                properties:
                  secretRef:
                    type: object
                    required:
                    - name
                    - key
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      key:
                        type: string
                  configMapRef:
                    type: object
                    required:
                    - name
                    - key
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      key:
                        type: string
              auth:
                description: Auth defines authentication configuration
                properties:
                  clientCertificateRef:
                    description: ClientCertificateRef points to secrets containing
                      client certificate and key for mTLS
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - name
                    type: object
                  kubeconfigSecretRef:
                    description: KubeconfigSecretRef points to a secret containing
                      kubeconfig
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - name
                    type: object
                  secretRef:
                    description: SecretRef points to a secret containing auth token
                    properties:
                      key:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - key
                    - name
                    type: object
                  serviceAccount:
                    description: ServiceAccount is the name of the service account
                      to use
                    type: string
                type: object
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
  scope: Cluster
  names:
    plural: clusteraccesses
    singular: clusteraccess
    kind: ClusterAccess
    shortNames:
    - ca
