with-expecter: true
packages:
  github.com/openmfp/crd-gql-gateway/kcp-listener/internal/apischema:
    config:
      dir: internal/apischema/mocks
      outpkg: mocks
    interfaces:
      Resolver:

  github.com/openmfp/crd-gql-gateway/kcp-listener/internal/discoveryclient:
    config:
      dir: internal/discoveryclient/mocks
      outpkg: mocks
    interfaces:
      Factory:

  github.com/openmfp/crd-gql-gateway/kcp-listener/internal/workspacefile:
    config:
      dir: internal/workspacefile/mocks
      outpkg: mocks
    interfaces:
      IOHandler:

  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      dir: internal/controller/mocks
      outpkg: mocks
    interfaces:
      Client: