name: ci
on: [push]

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-golang-module.yml@main
    secrets: inherit
    with:
      useLocalCoverageConfig: true
      coverageThreasholdFile: 0
      coverageThreasholdPackage: 0
      coverageThreasholdTotal: 0
